FROM golang:latest AS build

ENV GOOS=linux \
  GOARCH=amd64 \
  CGO_ENABLED=0

WORKDIR /app

ARG GOOGLE_APPLICATION_CREDENTIALS_STR
RUN echo $GOOGLE_APPLICATION_CREDENTIALS_STR > /tmp/serviceAccount.json
COPY go.mod .
RUN go mod download

COPY . .

RUN go build -o main

FROM scratch
COPY --from=golang:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build /tmp/serviceAccount.json /tmp/serviceAccount.json
COPY --from=build /app/main /main

CMD ["/main"]
