version: "3"

services:
  backend-production:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile.production
      args:
        - GOOGLE_APPLICATION_CREDENTIALS_STR=${GOOGLE_APPLICATION_CREDENTIALS_STR}
    container_name: kakure-handy-backend-production
    ports:
      - 8000:8000

  frontend-production:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile.production
      args:
        - FIREBASE_API_KEY=${FIREBASE_API_KEY}
        - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
        - BACKEND_URL=${BACKEND_URL}
    container_name: kakure-handy-frontend-production
    volumes:
      - ./docker/frontend/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
