FROM node:latest AS build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
RUN yarn install

COPY . .
ARG FIREBASE_API_KEY
ARG FIREBASE_AUTH_DOMAIN
ARG BACKEND_URL
RUN yarn build

FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
