INSERT INTO menu_item (category_id, name, price) VALUES (1, "旬野菜の彩りサラダ オレンジドレッシング", 850);
INSERT INTO menu_item (category_id, name, price) VALUES (1, "水菜とくみあげゆばのサラダ オリジナル和風ドレッシング", 900);
INSERT INTO menu_item (category_id, name, price) VALUES (1, "スモークサーモンとアボカドのシーザーサラダ", 950);
INSERT INTO menu_item (category_id, name, price) VALUES (2, "鶏そぼろ奴っこ", 600);
INSERT INTO menu_item (category_id, name, price) VALUES (2, "くみ上げ湯葉", 650);
INSERT INTO menu_item (category_id, name, price) VALUES (2, "鯛のからすみ和え", 800);
INSERT INTO menu_item (category_id, name, price) VALUES (2, "ほたるいかの沖漬け", 650);
INSERT INTO menu_item (category_id, name, price) VALUES (2, "さばへしこ", 600);
INSERT INTO menu_item (category_id, name, price) VALUES (2, "京漬物の盛り合わせ", 650);
INSERT INTO menu_item (category_id, name, price) VALUES (2, "チャンジャクリームチーズ", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (3, "生麩とベーコンの九条葱バター醤油焼き", 950);
INSERT INTO menu_item (category_id, name, price) VALUES (3, "生麩の揚げ出し", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (3, "エビのマヨネーズソース", 900);
INSERT INTO menu_item (category_id, name, price) VALUES (3, "京赤地鶏の塩焼き", 1200);
INSERT INTO menu_item (category_id, name, price) VALUES (3, "鴨肉黒七味焼き", 1500);
INSERT INTO menu_item (category_id, name, price) VALUES (3, "和牛レアステーキ", 2400);
INSERT INTO menu_item (category_id, name, price) VALUES (4, "ぶぶ漬け 鮭", 600);
INSERT INTO menu_item (category_id, name, price) VALUES (4, "ぶぶ漬け 梅", 500);
INSERT INTO menu_item (category_id, name, price) VALUES (4, "ぶぶ漬け 明太子", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (4, "ぶぶ漬け ちりめん山椒", 650);
INSERT INTO menu_item (category_id, name, price) VALUES (4, "京風湯葉あんかけにゅうめん", 800);
INSERT INTO menu_item (category_id, name, price) VALUES (4, "あぶり鯖寿司(4カン)", 1200);
INSERT INTO menu_item (category_id, name, price) VALUES (4, "赤出汁", 400);
INSERT INTO menu_item (category_id, name, price) VALUES (5, "ほうじ茶プリン", 500);
INSERT INTO menu_item (category_id, name, price) VALUES (5, "抹茶アイス", 450);
INSERT INTO menu_item (category_id, name, price) VALUES (5, "黒ごまアイス", 450);
INSERT INTO menu_item (category_id, name, price) VALUES (6, "付き出し", 600);
INSERT INTO menu_item (category_id, name, price) VALUES (7, "生ビール(キリン一番絞り) <中>", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (7, "瓶ビール(クラシックラガー)", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (7, "キリン零ICHI(ノンアルコール)", 600);
INSERT INTO menu_item (category_id, name, price) VALUES (8, "シーバスリーガル ロック", 850);
INSERT INTO menu_item (category_id, name, price) VALUES (8, "シーバスリーガル 水割り", 850);
INSERT INTO menu_item (category_id, name, price) VALUES (8, "シーバスリーガル ソーダ", 850);
INSERT INTO menu_item (category_id, name, price) VALUES (8, "シーバスリーガル その他", 850);
INSERT INTO menu_item (category_id, name, price) VALUES (8, "山崎 ロック", 900);
INSERT INTO menu_item (category_id, name, price) VALUES (8, "山崎 水割り", 900);
INSERT INTO menu_item (category_id, name, price) VALUES (8, "山崎 ソーダ", 900);
INSERT INTO menu_item (category_id, name, price) VALUES (8, "山崎 その他", 900);
INSERT INTO menu_item (category_id, name, price) VALUES (9, "黒烏龍茶", 550);
INSERT INTO menu_item (category_id, name, price) VALUES (9, "コカコーラ", 450);
INSERT INTO menu_item (category_id, name, price) VALUES (9, "ジンジャエール(甘口)", 450);
INSERT INTO menu_item (category_id, name, price) VALUES (9, "ジンジャエール(辛口)", 450);
INSERT INTO menu_item (category_id, name, price) VALUES (9, "オレンジジュース", 450);
INSERT INTO menu_item (category_id, name, price) VALUES (9, "グレープフルーツジュース", 450);
INSERT INTO menu_item (category_id, name, price) VALUES (9, "梅ジュース 水割り", 450);
INSERT INTO menu_item (category_id, name, price) VALUES (9, "梅ジュース ソーダ", 450);
INSERT INTO menu_item (category_id, name, price) VALUES (9, "マンゴジュース", 450);
INSERT INTO menu_item (category_id, name, price) VALUES (9, "緑茶(玉露)", 450);
INSERT INTO menu_item (category_id, name, price) VALUES (10, "京まんざら(京都)純米酒", 800);
INSERT INTO menu_item (category_id, name, price) VALUES (10, "伯楽星(宮城)純米酒吟醸", 1000);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "井田萬力(大分) ロック", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "井田萬力(大分) 水割り", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "井田萬力(大分) ソーダ", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "井田萬力(大分) その他", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "井田萬力(大分) 四合瓶", 4500);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "兼八(宮崎) ロック", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "兼八(宮崎) 水割り", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "兼八(宮崎) ソーダ", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "兼八(宮崎) その他", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "兼八(宮崎) 四合瓶", 4800);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "百年の孤独 ロック", 1000);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "百年の孤独 水割り", 1000);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "百年の孤独 ソーダ", 1000);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "百年の孤独 その他", 1000);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "八海山(新潟) ロック", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "八海山(新潟) 水割り", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "八海山(新潟) ソーダ", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "八海山(新潟) その他", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "㐂六(鹿児島) ロック", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "㐂六(鹿児島) 水割り", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "㐂六(鹿児島) ソーダ", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "㐂六(鹿児島) その他", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "㐂六(鹿児島) 四合瓶", 4500);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "富乃宝山(鹿児島) ロック", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "富乃宝山(鹿児島) 水割り", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "富乃宝山(鹿児島) ソーダ", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "富乃宝山(鹿児島) その他", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "富乃宝山(鹿児島) 四合瓶", 4800);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "朝日(鹿児島) ロック", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "朝日(鹿児島) 水割り", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "朝日(鹿児島) ソーダ", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (11, "朝日(鹿児島) その他", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "七年熟成梅酒青谷の梅(京都) ロック", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "七年熟成梅酒青谷の梅(京都) 水割り", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "七年熟成梅酒青谷の梅(京都) ソーダ", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "七年熟成梅酒青谷の梅(京都) その他", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "あらごし梅酒(奈良) ロック", 750);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "あらごし梅酒(奈良) 水割り", 750);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "あらごし梅酒(奈良) ソーダ", 750);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "あらごし梅酒(奈良) その他", 750);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "うぐいすとまり鶯とろ(福岡) ロック", 750);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "うぐいすとまり鶯とろ(福岡) 水割り", 750);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "うぐいすとまり鶯とろ(福岡) ソーダ", 750);
INSERT INTO menu_item (category_id, name, price) VALUES (12, "うぐいすとまり鶯とろ(福岡) その他", 750);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "ゆず酒 ロック", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "ゆず酒 水割り", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "ゆず酒 ソーダ", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "ゆず酒 その他", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "みかん ロック", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "みかん 水割り", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "みかん ソーダ", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "みかん その他", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "シークァーサー ロック", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "シークァーサー 水割り", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "シークァーサー ソーダ", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (13, "シークァーサー その他", 700);
INSERT INTO menu_item (category_id, name, price) VALUES (14, "モエ・エ・シャンドン <full>", 9800);
INSERT INTO menu_item (category_id, name, price) VALUES (14, "ブリュット・アンペリアル <half>", 6000);
INSERT INTO menu_item (category_id, name, price) VALUES (14, "リースリング", 5000);
INSERT INTO menu_item (category_id, name, price) VALUES (14, "ミュスカデ・セーヴル・メーヌ シュール・リー", 5500);
INSERT INTO menu_item (category_id, name, price) VALUES (14, "シャブリ", 6300);
INSERT INTO menu_item (category_id, name, price) VALUES (14, "ヴィーニ・ヴェルト・ルージュ", 5000);
INSERT INTO menu_item (category_id, name, price) VALUES (14, "ドメーヌ・ド・ラ・ガランス キュヴェ・風(KAZE)ルージュ", 6000);
INSERT INTO menu_item (category_id, name, price) VALUES (14, "レ ザルミエール", 8500);
