export { ForgetPassword } from './ForgetPassword';
export { LogIn } from './LogIn';
export { MailSent } from './MailSent';
export { NewOrder } from './NewOrder';
export { NewTable } from './NewTable';
export { NewOrderSuccess } from './NewOrderSuccess';
export { TableDetail } from './Table';
export { Tables } from './Tables';
export { Top } from './Top';
